### ISSUE TITLE
Add tag to each build

### ISSUE THREAD

**Issue by mcgee** [presidentio/teamcity-matrix-build-plugin#1]
Hi, thank you for plugin!
Is it possible to configure automatic tagging of builds? For instance if I have build parameters "Target=Stable,Unstable,Smoke", I would like to tag matrix builds as "Stable", "Unstable" and "Smoke" respectively.

**Comment by mcgee** [comment]
I realized that it's actually not neccessary because it is possible to use "Add tag" meta runner (https://github.com/JetBrains/meta-runner-power-pack) as first step.

**Comment by jdanekrh** [comment]
Patch is not necessary, but the possibility of adding a meta runner to achieve it should be documented in the README.
