### ISSUE TITLE
Question: Why does the matrix plugin require a build agent for the entire build duration?

### ISSUE THREAD

**Issue by CosminGramada** [presidentio/teamcity-matrix-build-plugin#10]
Let's say that I have for example my matrix the following way (with Only diagonal option checked):

```
os.name=windows,android
os.version=10,7.0
browser.name=chrome,android
browser.version=64,null
device=null,Samsung Galaxy S8 Plus
```

This matrix will spawn two jobs, but require 3 agents: 1 for each job and another 1 for the matrix.

However, as soon as the two jobs are started, the matrix job is still "running" until both jobs are completed, keeping an agent occupied for the entire duration.

In case there are only 2 agents available, 1 is occupied with the matrix, 1 is running the first job and the second job is queued.

So, my question is, why is there an agent required for the matrix job since it's either starting all the "spawned" jobs if there are enough agents, or it's queuing the rest?

**Comment by presidentio** [comment]
Hello, you are right. We have one agent used for coordinating of child builds. It's required for two actions: 
1) to trigger child builds 
2) to cancel them if something. 

So we could not avoid using separate agent for first action. But, we could do for the second one. To free agent after coordinator trigger child builds you can disable checkbox "Wait builds finish".
