### ISSUE TITLE
List of builds triggered by Matrix are no longer displayed in the latest version

### ISSUE THREAD

**Issue by CosminGramada** [presidentio/teamcity-matrix-build-plugin#11]
We have upgraded our TC server and it seems that the builds triggered by the Matrix plugin are no longer displayed under the Matrix tab.

New version: TeamCity Professional 2018.1 (build 58245)

**Comment by fduvoux** [comment]
I got the same issue ( #12 ) :-(

**Comment by fduvoux** [comment]
FYI, I propose a fix for this issue in my fork here : https://github.com/fduvoux/teamcity-matrix-build-plugin/tree/fix-2018-1-branch
I requested a pull to have it in main repository

**Comment by presidentio** [comment]
Closing as it was fixed in proposed PR

**Comment by jpmnteiro** [comment]
@presidentio any chance of creating a new release with this fix?

**Comment by presidentio** [comment]
@jpmnteiro I have published new release with fix for your issue
