### ISSUE TITLE
Issue with TC-2018-1  (build 58245)

### ISSUE THREAD

**Issue by fduvoux** [presidentio/teamcity-matrix-build-plugin#12]
Since I updated my TC server plugin is not working anymore.
Seems that matrix tab is not working anymore and build is mark as success while child build are failing (event with "wait child build finished" activated)

**Comment by fduvoux** [comment]
map.get(SettingsConst.PROP_CONST_BUILD_PARAMETERS) is giving null ptr in MatrixBuildRunTypePropertiesProcessor class

**Comment by presidentio** [comment]
Hello @fduvoux. Thanks for your contribution to this plugin. I'm really excited to see people use it. 
But, unfortunately, I don't have time to work on it, at least for now. If you can create a PR with fix, I will look on it and merge.

**Comment by fduvoux** [comment]
Hi,

I created a PR with a fix I made last night.
CI is not working but seems not to be related to my PR.
If you can have a look, it works pretty well on my 2 TC servers.

Regards,
______________
Fabien DUVOUX

**Comment by presidentio** [comment]
Looks well. Thanks for you contribution.
