### ISSUE TITLE
Triggering a matrix on a branch spawns builds on master branch only

### ISSUE THREAD

**Issue by jbakosi** [presidentio/teamcity-matrix-build-plugin#6]
When I trigger a matrix build, the child builds test the master branch instead of the feature branch the matrix was triggered on. How do I tell TeamCity and/or the matrix plugin to spawn the individual builds of a matrix checking out the branch the matrix was triggered with?

**Comment by presidentio** [comment]
Hi, thanks for interesting in my plugin. I think that it doesn't work properly, because this part of logic was implemented roughly and wasn't tested. 
I will appreciate if anybody can look on this. Else, I'll try to fix it once I have free time.

**Comment by jbakosi** [comment]
Cool, thanks! Please let me know if you want me to test. Thanks.

**Comment by tzz** [comment]
@presidentio can you point which classes and file(s) need to be modified to support non-default branches? I'd like to implement this but need to know where to start. Thank you.

**Comment by presidentio** [comment]
@tzz I guess it can be done in class https://github.com/presidentio/teamcity-matrix-build-plugin/blob/master/matrix-build-agent/src/main/java/com/presidentio/teamcity/matrix/build/agent/plan/BuildPlan.java in method createBuild which is responsible for configuring new build

**Comment by presidentio** [comment]
@jbakosi @tzz Please, test release https://github.com/presidentio/teamcity-matrix-build-plugin/releases/tag/v1.0.1 which contains this feature. If it works for you, I'll close this issue

**Comment by tzz** [comment]
I verified that the new code triggers the right branch. Very cool, thanks for implementing that!
