### ISSUE TITLE
string parser null exception on clearing parameters

### ISSUE THREAD

**Issue by tzz** [presidentio/teamcity-matrix-build-plugin#8]
If I enter some "constant build parameters" everything works.

If I remove them (clear the text box) I get a stack trace "null pointer exception" from the string parser and a 500 error from the TC server. If I enter `ignore=this` as constant build parameters, things work again. So it seems to be a parsing issue, easy to replicate.

**Comment by presidentio** [comment]
@tzz  I'm sorry I don't have a time to work on this plugin. If you have time to prepare PR, I will be glad to review it and merge

**Comment by tzz** [comment]
No worries. Thank you for working on this.
